# -*- mode: ruby -*-
# vi: set ft=ruby :

$install_ansible = <<SCRIPT
echo "##### Check for updates #####"
yum update  
SCRIPT

$setup_security = <<SCRIPT
echo "##### Add vagrant user to sudo groups ####"
usermod -aG sudo vagrant

echo "vagrant        ALL=(ALL)       NOPASSWD: ALL" >> /etc/sudoers
sed -i "s/^.*requiretty/#Defaults requiretty/" /etc/sudoers
SCRIPT

# Define Vagrant configuration version (2):
Vagrant.configure(2) do |config|
	#config.vm.synced_folder ".", "/vagrant"
	config.vm.define "jenkins-docker" do |machine|
	  machine.vm.box = "dotronglong/jenkins-docker"
	  machine.vm.box_version = "2.0.0"
 	  machine.vm.hostname = "jenkins-docker.local.com"
 	  machine.vm.network "private_network", ip: "192.168.188.10"
 	  machine.vm.synced_folder ".", "/vagrant"
 	  machine.vm.provider "virtualbox" do |vb|
		vb.customize ["modifyvm", :id, "--name", "jenkins-docker"]
		vb.memory = "2048"
		vb.cpus = "2"
		vb.name = "jenkins-docker"
	  end	
		machine.vm.provision "shell", inline: "echo '####### Provision Jenkins on Docker VM #######'"
		machine.vm.provision :file, source: "." , destination: "/vagrant/"
		#Another way to do the provisioning
		#machine.vm.provision "ansible" do |apb| 
        #     apb.playbook = "drybox-playbook.yml"
		#end	 
	end
end	











